In [4]:
import matplotlib.pyplot as plt
import numpy as np
import yfinance as yf
from keras.layers import Input, LSTM, Dense
from keras.models import Sequential
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.preprocessing import MinMaxScaler


# Fetch stock market data
def fetch_data(ticker, start_date, end_date):
    return yf.download(ticker, start=start_date, end=end_date)


# Prepare time-series data
def create_dataset(dataset, look_back=60):
    X, y = [], []
    for i in range(len(dataset) - look_back - 1):
        a = dataset[i:(i + look_back), 0]
        X.append(a)
        y.append(dataset[i + look_back, 0])
    return np.array(X), np.array(y)


# Fetch data for training
ticker = "^GSPC"
start_date = "2023-01-01"
end_date = "2023-12-31"
data = fetch_data(ticker, start_date, end_date)

data

[*********************100%***********************]  1 of 1 completed

Price             Close         High          Low         Open      Volume
Ticker            ^GSPC        ^GSPC        ^GSPC        ^GSPC       ^GSPC
Date
2023-01-03  3824.139893  3878.459961  3794.330078  3853.290039  3959140000
2023-01-04  3852.969971  3873.159912  3815.770020  3840.360107  4414080000
2023-01-05  3808.100098  3839.739990  3802.419922  3839.739990  3893450000
2023-01-06  3895.080078  3906.189941  3809.560059  3823.370117  3923560000
2023-01-09  3892.090088  3950.570068  3890.419922  3910.820068  4311770000
...                 ...          ...          ...          ...         ...
2023-12-22  4754.629883  4772.939941  4736.770020  4753.919922  3046770000
2023-12-26  4774.750000  4784.720215  4758.450195  4758.859863  2513910000
2023-12-27  4781.580078  4785.390137  4768.899902  4773.450195  2748450000
2023-12-28  4783.350098  4793.299805  4780.979980  4786.439941  2698860000
2023-12-29  4769.830078  4788.430176  4751.990234  4782.879883  3126060000

[250 rows x 5 columns]